[package]
name = "rackdevops"
version = "1.0.0"
description = "RackDevOps - Diseño de Infraestructura de Red"

[app]
name = "rackdevops-app"
source = "."

[[app.manifests]]
type = "node"
build_command = "npm run build"
start_command = "npm run start"
env = { NODE_ENV = "production" }